# Generated by Django 4.2.5 on 2023-10-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=1352, max_length=50, verbose_name='ключ'),
        ),
    ]
