# Generated by Django 4.2.5 on 2023-10-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ключ'),
        ),
    ]
