# Generated by Django 4.2.7 on 2023-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_email_verify_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'администратор'), ('moderator', 'модератор'), ('member', 'участник')], default='участник', max_length=10, verbose_name='роль'),
        ),
    ]
