# Generated by Django 4.2.7 on 2023-11-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'администратор'), ('moderator', 'модератор'), ('member', 'участник')], default='участник', max_length=15, verbose_name='роль'),
        ),
    ]
