# Generated by Django 4.2.7 on 2023-11-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_status_of_product', 'Can status_of_product'), ('set_description', 'Can description'), ('set_category_product', 'Can category_product')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
