# Generated by Django 4.2.7 on 2023-11-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('set_product_status', 'Can product_status'), ('set_product_description', 'Can product_description'), ('set_product_category', 'Can product_category')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
