# Generated by Django 4.2.5 on 2023-09-18 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_remove_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('img_preview', models.ImageField(upload_to='blog_post_preview/', verbose_name='превью изображения')),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='дата создания')),
                ('is_published', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('view_count', models.IntegerField(verbose_name='количество просмотров')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ('title',),
            },
        ),
    ]
