# Generated by Django 4.2.5 on 2023-09-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.CharField(max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
