# Generated by Django 4.2.5 on 2023-09-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_blogpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img_preview',
            field=models.ImageField(upload_to='post_preview/', verbose_name='превью изображения'),
        ),
    ]
