# Generated by Django 4.2.5 on 2023-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_post_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_preview',
            field=models.ImageField(blank=True, null=True, upload_to='post_preview/', verbose_name='превью изображения'),
        ),
    ]
