# Generated by Django 4.2.5 on 2023-09-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_post_create_date_alter_post_img_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug'),
        ),
    ]
